version: '3.8'

services:
  # PostgreSQL для хранения данных Airflow
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    ne

  # Инициализатор базы данных Airflow
  airflow-init:
      build:
        context: . 
        dockerfile: Dockerfile
        target: initializer  # multistage цель initializer
      environment:
        AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
        AIRFLOW_ADMIN_USER: ${AIRFLOW_ADMIN_USER}
        AIRFLOW_ADMIN_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
      depends_on:
        - postgres
      command: >
        bash -c "airflow db upgrade &&
                airflow users create -u ${AIRFLOW_ADMIN_USER} -p ${AIRFLOW_ADMIN_PASSWORD} -r Admin -e ${AIRFLOW_ADMIN_EMAIL} -f Admin -l User ||
                echo 'Admin user already exists' &&
                airflow webserver & airflow scheduler"

  # Веб-сервер Airflow
  airflow-webserver:
    build:
      context: . 
      dockerfile: Dockerfile
      target: production  
    container_name: airflow_server
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW_UID: "50000"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: ["airflow", "webserver"]
    restart: always

  # Планировщик задач Airflow (Scheduler)
  airflow-scheduler:
    build:
      context: .  
      dockerfile: Dockerfile
      target: production  
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW_UID: "50000"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: ["airflow", "scheduler"]
    restart: always

volumes:
  postgres_data:
  airflow_logs:
  airflow_plugins:
