apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-configmap
  labels:
    app: airflow
data:
  POSTGRES_DB: "airflow"
  POSTGRES_HOST: "postgres-service"
  AIRFLOW_ADMIN_USER: "admin"
  AIRFLOW_ADMIN_PASSWORD: "admin"
  AIRFLOW_ADMIN_EMAIL: "admin_example@com"
  AIRFLOW_EXECUTOR: "LocalExecutor"
  AIRFLOW_HOME: "/opt/airflow"