kubectl delete -f configmap.yml
kubectl delete -f pg_secret.yml
kubectl delete -f pg_pvc.yml
kubectl delete -f jupyter_deployment.yml
kubectl delete -f pg_deployment.yml
kubectl delete -f pg_service.yml
kubectl delete -f jupyter_service.yml
kubectl get pods --show-labels
kubectl get services --show-labels
kubectl describe pvc pg_pvc