apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook-service
  labels:
    app: jupyter-notebook
    part: frontend
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30000
  selector:
    app: jupyter-notebook